In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("Injury Raw Data.csv")

In [3]:
df.head(3)

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,cumulative_games_played,minutes_per_game_prev_seasons,avg_days_injured_prev_seasons,avg_games_per_season_prev_seasons,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season
0,aaronconnolly,2019,13,161,1312,24,28,2148,41,1/28/2000,...,NaN,NaN,NaN,NaN,24.613627,2.5,2.0,NaN,NaN,NaN
1,aaronconnolly,2020,71,161,836,17,28,2148,41,1/28/2000,...,24.0,54.666667,13.0,24.0,24.613627,2.5,2.0,0.0,161.0,13.0
2,aaroncresswell,2016,95,226,2247,26,27,13368,149,12/15/1989,...,NaN,NaN,NaN,NaN,22.396079,3.5,1.0,NaN,NaN,NaN

In [4]:
df.tail(5)

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,cumulative_games_played,minutes_per_game_prev_seasons,avg_days_injured_prev_seasons,avg_games_per_season_prev_seasons,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season
1296,yoshinorimuto,2019,46,210,288,8,17,915,25,7/15/1992,...,17.0,36.882353,40.0,17.0,22.597274,4.0,2.0,0.0,210.0,40.0
1297,yvesbissouma,2018,124,124,1880,28,34,6477,86,8/30/1996,...,NaN,NaN,NaN,NaN,24.151673,3.5,3.0,NaN,NaN,NaN
1298,zacksteffen,2020,30,307,95,1,35,95,1,4/2/1995,...,NaN,NaN,NaN,NaN,23.244977,3.0,0.0,NaN,NaN,NaN
1299,zlatanibrahimovic,2016,210,579,2577,28,28,2699,33,10/3/1981,...,NaN,NaN,NaN,NaN,24.983563,2.5,2.0,NaN,NaN,NaN
1300,zlatanibrahimovic,2017,84,579,122,5,8,2699,33,10/3/1981,...,28.0,92.035714,210.0,28.0,24.983563,2.5,2.0,1.0,579.0,210.0

In [5]:
df.describe()

,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,height_cm,weight_kg,...,cumulative_games_played,minutes_per_game_prev_seasons,avg_days_injured_prev_seasons,avg_games_per_season_prev_seasons,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season
count,1301.000000,1301.000000,1301.000000,1301.000000,1301.000000,1301.000000,1301.000000,1301.000000,1301.000000,1301.000000,...,697.000000,685.000000,697.000000,697.000000,1301.000000,1301.000000,1299.000000,697.000000,697.000000,697.000000
mean,2018.099923,79.050730,260.710992,1483.156034,19.509608,25.089931,5533.593390,71.638739,182.516205,76.833935,...,53.279770,74.541947,79.501987,21.952038,23.039310,3.346272,1.823711,0.225251,786.351506,81.279770
std,1.384810,84.578169,202.741896,1014.013920,11.099727,10.157698,4095.421082,46.854260,6.821092,7.362975,...,63.111519,17.856054,71.057640,9.408793,1.470255,0.392971,0.999472,0.418048,1064.323175,84.353614
min,2016.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,163.000000,58.000000,...,0.000000,7.000000,2.000000,0.000000,18.792451,2.500000,0.000000,0.000000,7.000000,0.000000
25%,2017.000000,24.000000,111.000000,612.000000,10.000000,19.000000,2012.000000,31.000000,178.000000,72.000000,...,23.000000,65.500000,29.000000,16.000000,22.093170,3.000000,1.000000,0.000000,191.000000,26.000000
50%,2018.000000,49.000000,210.000000,1440.000000,21.000000,28.000000,5023.000000,69.000000,183.000000,76.000000,...,35.000000,80.080645,60.500000,23.000000,23.074830,3.500000,2.000000,0.000000,427.000000,50.000000
75%,2019.000000,103.000000,370.000000,2311.000000,29.000000,33.000000,8387.000000,107.000000,187.666667,82.000000,...,64.000000,87.925926,111.500000,29.000000,23.947116,3.500000,3.000000,0.000000,903.000000,109.000000
max,2020.000000,702.000000,2398.000000,3610.000000,38.000000,54.000000,16768.000000,179.000000,203.000000,99.000000,...,508.000000,95.000000,702.000000,38.000000,28.525475,4.000000,3.000000,1.000000,7590.000000,702.000000

In [6]:
df.describe(include="object")

            p_id2        dob nationality      work_rate  position
count        1301       1301        1301           1301      1299
unique        604        588          61              8         4
top     bendavies  6/22/1993     England  Medium/Medium  Defender
freq           24          9         551            434       492

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 30 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   p_id2                              1301 non-null   object
 1   start_year                         1301 non-null   int64
 2   season_days_injured                1301 non-null   int64
 3   total_days_injured                 1301 non-null   int64
 4   season_minutes_played              1301 non-null   int64
 5   season_games_played                1301 non-null   int64
 6   season_matches_in_squad            1301 non-null   int64
 7   total_minutes_played               1301 non-null   int64
 8   total_games_played                 1301 non-null   int64
 9   dob                                1301 non-null   object
 10  height_cm                          1301 non-null   float64
 11  weight_kg                          1301 non-null   float64
 12  nationality                        1301 non-null   object
 13  work_rate                          1301 non-null   object
 14  pace                               1206 non-null   float64
 15  physic                             1206 non-null   float64
 16  fifa_rating                        1301 non-null   float64
 17  position                           1299 non-null   object
 18  age                                1301 non-null   int64
 19  cumulative_minutes_played          697 non-null    float64
 20  cumulative_games_played            697 non-null    float64
 21  minutes_per_game_prev_seasons      685 non-null    float64
 22  avg_days_injured_prev_seasons      697 non-null    float64
 23  avg_games_per_season_prev_seasons  697 non-null    float64
 24  bmi                                1301 non-null   float64
 25  work_rate_numeric                  1301 non-null   float64
 26  position_numeric                   1299 non-null   float64
 27  significant_injury_prev_season     697 non-null    float64
 28  cumulative_days_injured            697 non-null    float64
 29  season_days_injured_prev_season    697 non-null    float64
dtypes: float64(16), int64(9), object(5)
memory usage: 305.1+ KB

In [8]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1296    False
1297    False
1298    False
1299    False
1300    False
Length: 1301, dtype: bool

In [9]:
df.duplicated().sum()

0

In [10]:
df.isnull()

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,cumulative_games_played,minutes_per_game_prev_seasons,avg_days_injured_prev_seasons,avg_games_per_season_prev_seasons,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1297,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
1298,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
1299,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
1300,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

p_id2                                  0
start_year                             0
season_days_injured                    0
total_days_injured                     0
season_minutes_played                  0
season_games_played                    0
season_matches_in_squad                0
total_minutes_played                   0
total_games_played                     0
dob                                    0
height_cm                              0
weight_kg                              0
nationality                            0
work_rate                              0
pace                                  95
physic                                95
fifa_rating                            0
position                               2
age                                    0
cumulative_minutes_played            604
cumulative_games_played              604
minutes_per_game_prev_seasons        616
avg_days_injured_prev_seasons        604
avg_games_per_season_prev_seasons    604
bmi                                    0
work_rate_numeric                      0
position_numeric                       2
significant_injury_prev_season       604
cumulative_days_injured              604
season_days_injured_prev_season      604
dtype: int64

In [12]:
df.dropna()

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,cumulative_games_played,minutes_per_game_prev_seasons,avg_days_injured_prev_seasons,avg_games_per_season_prev_seasons,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season
1,aaronconnolly,2020,71,161,836,17,28,2148,41,1/28/2000,...,24.0,54.666667,13.000000,24.000000,24.613627,2.5,2.0,0.0,161.0,13.0
3,aaroncresswell,2018,87,226,1680,20,27,13368,149,12/15/1989,...,26.0,86.423077,95.000000,26.000000,22.396079,3.5,1.0,0.0,226.0,95.0
4,aaroncresswell,2019,35,226,2870,31,31,13368,149,12/15/1989,...,46.0,85.369565,91.000000,23.000000,22.396079,3.5,1.0,0.0,452.0,87.0
5,aaroncresswell,2020,9,226,3342,36,36,13368,149,12/15/1989,...,77.0,88.272727,72.333333,25.666667,22.396079,3.5,1.0,0.0,678.0,35.0
7,aaronlennon,2018,166,199,1279,16,16,4371,72,4/16/1987,...,29.0,68.827586,33.000000,29.000000,23.140496,4.0,3.0,0.0,199.0,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1291,yerrymina,2019,54,427,2421,29,31,5412,66,9/23/1994,...,13.0,72.846154,158.000000,13.000000,23.592231,3.0,1.0,1.0,427.0,158.0
1292,yerrymina,2020,83,427,2044,24,30,5412,66,9/23/1994,...,42.0,80.190476,106.000000,21.000000,23.592231,3.0,1.0,0.0,854.0,54.0
1294,yohancabaye,2017,48,64,2467,31,33,4694,63,1/14/1986,...,32.0,69.593750,16.000000,32.000000,23.361325,3.0,3.0,0.0,64.0,16.0
1296,yoshinorimuto,2019,46,210,288,8,17,915,25,7/15/1992,...,17.0,36.882353,40.000000,17.000000,22.597274,4.0,2.0,0.0,210.0,40.0
1300,zlatanibrahimovic,2017,84,579,122,5,8,2699,33,10/3/1981,...,28.0,92.035714,210.000000,28.000000,24.983563,2.5,2.0,1.0,579.0,210.0

In [13]:
df.dropna(axis =1 )

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,height_cm,weight_kg,nationality,work_rate,fifa_rating,age,bmi,work_rate_numeric
0,aaronconnolly,2019,13,161,1312,24,28,2148,41,1/28/2000,175.333333,75.666667,Republic of Ireland,Medium/Low,63.000000,19,24.613627,2.5
1,aaronconnolly,2020,71,161,836,17,28,2148,41,1/28/2000,175.333333,75.666667,Republic of Ireland,Medium/Low,63.000000,20,24.613627,2.5
2,aaroncresswell,2016,95,226,2247,26,27,13368,149,12/15/1989,171.666667,66.000000,England,High/Medium,75.333333,27,22.396079,3.5
3,aaroncresswell,2018,87,226,1680,20,27,13368,149,12/15/1989,171.666667,66.000000,England,High/Medium,75.333333,29,22.396079,3.5
4,aaroncresswell,2019,35,226,2870,31,31,13368,149,12/15/1989,171.666667,66.000000,England,High/Medium,75.333333,30,22.396079,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,yoshinorimuto,2019,46,210,288,8,17,915,25,7/15/1992,178.500000,72.000000,Japan,High/High,74.333333,27,22.597274,4.0
1297,yvesbissouma,2018,124,124,1880,28,34,6477,86,8/30/1996,182.000000,80.000000,Mali,High/Medium,73.000000,22,24.151673,3.5
1298,zacksteffen,2020,30,307,95,1,35,95,1,4/2/1995,191.000000,84.800000,United States,Medium/Medium,72.000000,25,23.244977,3.0
1299,zlatanibrahimovic,2016,210,579,2577,28,28,2699,33,10/3/1981,195.000000,95.000000,Sweden,Medium/Low,86.666667,35,24.983563,2.5
1300,zlatanibrahimovic,2017,84,579,122,5,8,2699,33,10/3/1981,195.000000,95.000000,Sweden,Medium/Low,86.666667,36,24.983563,2.5

In [14]:
df = df.bfill()

In [15]:
df

,p_id2,start_year,season_days_injured,total_days_injured,season_minutes_played,season_games_played,season_matches_in_squad,total_minutes_played,total_games_played,dob,...,cumulative_games_played,minutes_per_game_prev_seasons,avg_days_injured_prev_seasons,avg_games_per_season_prev_seasons,bmi,work_rate_numeric,position_numeric,significant_injury_prev_season,cumulative_days_injured,season_days_injured_prev_season
0,aaronconnolly,2019,13,161,1312,24,28,2148,41,1/28/2000,...,24.0,54.666667,13.0,24.0,24.613627,2.5,2.0,0.0,161.0,13.0
1,aaronconnolly,2020,71,161,836,17,28,2148,41,1/28/2000,...,24.0,54.666667,13.0,24.0,24.613627,2.5,2.0,0.0,161.0,13.0
2,aaroncresswell,2016,95,226,2247,26,27,13368,149,12/15/1989,...,26.0,86.423077,95.0,26.0,22.396079,3.5,1.0,0.0,226.0,95.0
3,aaroncresswell,2018,87,226,1680,20,27,13368,149,12/15/1989,...,26.0,86.423077,95.0,26.0,22.396079,3.5,1.0,0.0,226.0,95.0
4,aaroncresswell,2019,35,226,2870,31,31,13368,149,12/15/1989,...,46.0,85.369565,91.0,23.0,22.396079,3.5,1.0,0.0,452.0,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,yoshinorimuto,2019,46,210,288,8,17,915,25,7/15/1992,...,17.0,36.882353,40.0,17.0,22.597274,4.0,2.0,0.0,210.0,40.0
1297,yvesbissouma,2018,124,124,1880,28,34,6477,86,8/30/1996,...,28.0,92.035714,210.0,28.0,24.151673,3.5,3.0,1.0,579.0,210.0
1298,zacksteffen,2020,30,307,95,1,35,95,1,4/2/1995,...,28.0,92.035714,210.0,28.0,23.244977,3.0,0.0,1.0,579.0,210.0
1299,zlatanibrahimovic,2016,210,579,2577,28,28,2699,33,10/3/1981,...,28.0,92.035714,210.0,28.0,24.983563,2.5,2.0,1.0,579.0,210.0
1300,zlatanibrahimovic,2017,84,579,122,5,8,2699,33,10/3/1981,...,28.0,92.035714,210.0,28.0,24.983563,2.5,2.0,1.0,579.0,210.0

In [16]:
df.isnull().sum()

p_id2                                0
start_year                           0
season_days_injured                  0
total_days_injured                   0
season_minutes_played                0
season_games_played                  0
season_matches_in_squad              0
total_minutes_played                 0
total_games_played                   0
dob                                  0
height_cm                            0
weight_kg                            0
nationality                          0
work_rate                            0
pace                                 0
physic                               0
fifa_rating                          0
position                             0
age                                  0
cumulative_minutes_played            0
cumulative_games_played              0
minutes_per_game_prev_seasons        0
avg_days_injured_prev_seasons        0
avg_games_per_season_prev_seasons    0
bmi                                  0
work_rate_numeric                    0
position_numeric                     0
significant_injury_prev_season       0
cumulative_days_injured              0
season_days_injured_prev_season      0
dtype: int64

In [17]:
df.to_csv("injury_output.csv" , index = False)